### ISSUE TITLE
Make Kaboom Plugin

### ISSUE THREAD

**Issue by niceEli** [neverUsedGithub/kaboom-flex-ui#1]
As the title states i beileve that kfu should become a kaboom plugin instead of a standalone thing you need to import in every script. with this you can just call k.kfu.$Box for example.

**Comment by neverUsedGithub** [comment]
Sounds like a good idea, but I would make the Kaboom instance have `$box`, `$text` itself without a `kfu` wrapper.

**Comment by neverUsedGithub** [comment]
The default export is now a plugin.

**Comment by niceEli** [comment]
👍
